### PR TITLE
Add support for Ubuntu 24.04

### LINKED ISSUE #467: Ubuntu 24.04 support

### PR DESCRIPTION
**Pull request by vilhelmprytz**
Fixes #467

### CODE REVIEW

**Review by Linux123123 — APPROVED** [review]
LGTM

**Comment by evokerking1** [comment]
ETA for merge?

**Comment by Exoticlegion** [comment]
ETA for 24.04 to be supported?

**Comment by vilhelmprytz** [comment]
We usually wait for the first "minor" release, meaning `24.04.1` in this case. But I'll see if we can speed things up, there were some problems with the Vagrant box (Ubuntu won't release Vagrant images anymore).

**Comment by vilhelmprytz** [comment]
@Linux123123 I changed the Vagrant box to an existing one (apparently Vagrant images have been dropped by the ubuntu team, see https://bugs.launchpad.net/cloud-images/+bug/2065126). I tested it as well and seems to work. OK to merge and release?

**Review by Linux123123 — APPROVED** [review]

**Comment by Linux123123** [comment]
Good to merge

**Pull request merged**
