### PR TITLE
Made enhancements

### PR DESCRIPTION
**Pull request by QXIoa**
- Added checks before rm -rfing files
- Added extra logging when allowing ports in firewall

### CODE REVIEW

**Comment by Linux123123** [comment]
Hello, thanks for PR everything looks good, except last commit you changed urls.

**Comment by QXIoa** [comment]
Alright! I changed it back to the correct URL in the latest commit. Please allow the pull request. Thanks!

**Review by Linux123123 — APPROVED** [review]
LGTM

**Comment by oie1** [comment]
> LGTM

"lgtm"
image

**Comment by QXIoa** [comment]
All I did was add some checks and enhancements

**Comment by QXIoa** [comment]
I didn't even modify the Vagrantfile + I'm not at fault for GitHub Actions forgetting what Vagrant is.

**Comment by oie1** [comment]
> I didn't even modify the Vagrantfile + I'm not at fault for GitHub Actions forgetting what Vagrant is.

your fault for getting your pr accepted at the same time github actions got dementia

**Comment by Linux123123** [comment]
GitHub actions vagrant have been broken for a long time and there is currently no fixing it easily.

**Comment by QXIoa** [comment]
So it's not my fault!

**Pull request merged**
