### PR TITLE
Update from php 8.1 to 8.3

### PR DESCRIPTION
**Pull request by SuperEvilLuke**
Updated PHP to 8.3 which is now used in the ptero docs

### CODE REVIEW

**Comment by Skyy-Development** [comment]
I agree.

**Comment by SuperEvilLuke** [comment]
Yeah, I forgot to update the readme lmao, only realised when i woke up this morning

**Review by lezetho — APPROVED** [review]
hi luke! yes you did it right congrats 🎉

**Comment by Linux123123** [comment]
The PR can't wait for Vilhelm as Pterodactyl released a new release, which only supports PHP 8.2 and above.

**Pull request merged**
